# Generated by Django 4.0.6 on 2022-08-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, unique=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('image', models.ImageField(upload_to='image_article')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
            ],
        ),
        migrations.CreateModel(
            name='Section_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.CreateModel(
            name='Image_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_post')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.section_post')),
            ],
        ),
    ]
