# Generated by Django 4.0.6 on 2022-09-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_post'),
        ),
        migrations.DeleteModel(
            name='Image_post',
        ),
    ]
