# Generated by Django 4.0.6 on 2022-09-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_section_post_image_delete_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section_post',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images_post'),
        ),
    ]
