# Generated by Django 4.0.6 on 2022-09-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_section_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='section_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_post'),
        ),
    ]
